version: 3
projects:
  - dir: infrastructure/aws/cloud-deployment/s3-tfstate
    apply_requirements: ["mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: infrastructure/aws/cloud-deployment/vpc
    apply_requirements: ["mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
      enabled: true
  - dir: infrastructure/aws/cloud-deployment/route53-ols
    apply_requirements: ["mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: infrastructure/aws/cloud-deployment/kms-ols
    apply_requirements: ["mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: infrastructure/aws/cloud-deployment/ec2-atlantis
    apply_requirements: ["mergeable"]
    autoplan:
      when_modified: ["*.tf*", "*.yml*"]
  - dir: infrastructure/aws/cloud-deployment/eks-ols
    apply_requirements: ["mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: infrastructure/aws/cloud-deployment/ec2-bastion
    apply_requirements: ["mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: infrastructure/aws/k8s-deployment/helm-external-dns
    apply_requirements: ["mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: infrastructure/aws/k8s-deployment/helm-argocd
    apply_requirements: ["mergeable"]
    autoplan:
      when_modified: ["*.tf*"]