version: 3
projects:
  - dir: cloud-deployment/vpc
    apply_requirements: ["approved", "mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
      enabled: true
  - dir: cloud-deployment/gcs_iac
    apply_requirements: ["approved", "mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: cloud-deployment/gke_cluster
    apply_requirements: ["approved", "mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: cloud-deployment/gcd_blast
    apply_requirements: ["approved", "mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: cloud-deployment/gsm_github_token
    apply_requirements: ["approved", "mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: cloud-deployment/gsm_github_webhook_secret
    apply_requirements: ["approved", "mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: k8s-deployment/helm_atlantis
    apply_requirements: ["approved", "mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: cloud-deployment/gce_bastion
    apply_requirements: ["approved", "mergeable"]
    autoplan:
      when_modified: ["*.tf*"]
  - dir: k8s-deployment/helm_nginx
    apply_requirements: ["approved", "mergeable"]
    autoplan:
      when_modified: ["*.tf*"]