---
- hosts: all
  tasks:
    - name: Get stable kubectl version
      command: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
      register: stable_version
      changed_when: false

    - name: Download kubectl
      become: yes
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ stable_version.stdout }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Check kubectl version
      command: kubectl version --client
      register: version
      changed_when: false

    - debug:
        var: version.stdout

    - name: Ensure .kube directory exists
      file:
        path: /home/debian/.kube
        state: directory
        owner: debian
        group: debian
        mode: '0755'

    - name: Write service account key to file
      copy:
        content: "{{ service_account_key }}"
        dest: "/home/debian/service_account_key.json"
        owner: debian
        group: debian
        mode: '0644'

    - name: Set GCP project
      command:
        cmd: gcloud config set project {{ project_id }}
      become: no

    - name: Authenticate using service account
      command:
        cmd: gcloud auth activate-service-account --key-file=/home/debian/service_account_key.json
      become: no

    - name: Get GKE cluster credentials to generate kubeconfig
      command:
        cmd: gcloud container clusters get-credentials {{ cluster_name }} --region {{ region }}
      become: no
