---
- hosts: all
  tasks:
    - name: Get stable kubectl version
      command: curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
      register: stable_version
      changed_when: false

    - name: Download kubectl
      become: yes
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ stable_version.stdout }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Check kubectl version
      command: kubectl version --client
      register: version
      changed_when: false

    - debug:
        var: version.stdout

    - name: Ensure .kube directory exists
      file:
        path: /home/debian/.kube
        state: directory
        owner: debian
        group: debian
        mode: '0755'

    - name: Setup kubeconfig
      copy:
        content: "{{ kubeconfig }}"
        dest: "/home/debian/.kube/config"
        owner: debian
        group: debian
        mode: '0644'
